version: '3.8'
services:
    lumen-skeleton:
        container_name: lumen-skeleton
        build:
            context: ./
        links:
            - mongo-poc
        ports:
            - "8080:80"
        networks:
            - network-poc
        volumes:
            - ./config/apache/default.conf:/etc/apache2/sites-enabled/default.conf
            - type: bind
              source: ./
              target: /var/www/html/app
             
volumes:
    src:
networks:
  network-poc:
    external: true
